### ISSUE TITLE
[Bug]:  Sensor "Active groups" become unavailable, when available an event "Group Active" is trigerred

### ISSUE THREAD

**Issue by 14FRS851** [mguyard/hass-diagral#53]
### The problem

Sometimes, the "Active groups" sensor becomes unavailable in my Home Assistant. When it becomes available again, the "group active" event is triggered, even if the value of "group active" hasn't changed since before the sensor became unavailable.

![Image](https://github.com/user-attachments/assets/0a6bd5ec-1f1f-4bbb-92cc-17b1a7d83f2e)

### Reproduction steps

1- Create a scenario that triggers a notification when a "group active change" event occurs.
2 - Activate your alarm.
3 - If the "group active" sensor becomes unavailable, when it becomes available again, a "group active change" event is triggered.

TODO: Repeat the same test with the alarm disabled and check if the event is triggered when no groups are active.

### What version of Home Assistant Core has the issue?

 	core-2025.6.1

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

I have a Home Assistant Yellow hardware

### Anything in the logs that might be useful for us?

```text

```

### Checklist

- [x] I have filled out the issue template to the best of my ability.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of currently [previous issues](https://github.com/mguyard/hass-diagral/issues?q=label%3Abug)..

**Comment by mguyard** [comment]
Bonjour,

J'ai moi aussi par moment des accès au Cloud Diagral qui ne semble pas répondre, raison pour laquelle les entités passent en unavailable. Jusque là c'est un comportement normal de HA.

Le fait qu'un event soit déclenché lorsque l'integration redonne de nouvelle valeur à HA est aussi un comportement normal de HA. Chaque changement de valeur déclenche un event.
Ensuite cet event est trigger par un scénario dans votre cas.

Dans ce cas particulier, il faudrait filtrer pour que l'automation ne déclenche pas les actions du scénario si l'état d'origine est unavailable. Même chose si l'état de destination est unavailable.

Avec une condition comme cela cela devrait marcher :

```yaml
condition: or
conditions:
  - condition: template
    value_template: "{{ trigger.from_state.state not in ['unknown', 'unavailable'] }}"
    alias: Si l'état d'origine est unavailable
  - condition: template
    value_template: "{{ trigger.to_state.state not in ['unknown', 'unavailable'] }}"
    alias: Si l'état de destination est unavailable
```
